version: '3.7'

services:
  lanchonete:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app/src
    working_dir: /app/src
    environment:
      - MONGODB_CONNECTION_STRING_PRODUTO=${MONGODB_CONNECTION_STRING_PRODUTO}
    networks:
      - default

networks:
  default:
    name: lanchonete_produto_network
