apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: danilocassola/fiap-lanchonete-produto:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: nodejs-app-secrets
                  key: MONGODB_URL
