name: Deploy Simulation to EKS

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths:
      - 'k8s/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Simulation to DockerHub"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Simulation to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name prod-lanchonete-cluster --region us-east-1
