name: Deploy Simulation Prod

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  deploy-to-dockerhub:
    name: Deploy Simulation to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u danilocassola -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t danilocassola/fiap-lanchonete-produto:v1.1 .

  deploy-to-eks:
    name: Deploy Simulation to EKS
    runs-on: ubuntu-latest
    needs: deploy-to-dockerhub

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name prod-lanchonete-cluster --region us-east-1
