name: Deploy to EKS

on:
  push:
    branches: ["main"]
    paths:
      - 'k8s/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to DockerHub"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name prod-lanchonete-cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f "k8s/configmap.yaml" -n lanchonete-produto
          kubectl apply -f "k8s/deployment.yaml" -n lanchonete-produto
          kubectl apply -f "k8s/service.yaml" -n lanchonete-produto
          kubectl apply -f "k8s/hpa.yaml" -n lanchonete-produto
